baseURL = 'https://rididbxeuebb.pages.dev'
languageCode = 'en'
title = 'rididbxeuebb'
disableKinds = ['taxonomy', 'term', 'section']

[markup]
[markup.highlight]
codeFences = true
guessSyntax = true
style = 'dracula'
noClasses = true

[params]
tagline = 'Powered by Neovim, black coffee, and unadulterated rage against modern web bloat.'
description = 'An unhinged dumping ground for a developer who is one npm install away from a psychotic break. No sanitized corporate bullshit, just pure terminal supremacy.'